# Generated by Django 3.1.3 on 2020-12-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdresDostawy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdresyZamieszkania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DaneKontaktowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_telefonu', models.CharField(max_length=9)),
                ('adres_mailowy', models.CharField(max_length=45)),
                ('fax', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanePlatnosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_platnosci', models.DateField()),
                ('metoda_platnosci', models.CharField(max_length=15)),
                ('status_platnosci', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dostawcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.IntegerField()),
                ('nazwisko', models.IntegerField()),
                ('pesel', models.IntegerField()),
                ('adresy_zamieszkania_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.adresyzamieszkania')),
                ('dane_kontaktowe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.danekontaktowe')),
            ],
        ),
        migrations.CreateModel(
            name='Restouracje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_restouracji', models.CharField(max_length=45)),
                ('numer_telefonu', models.IntegerField()),
                ('nip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusDostawcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_umowy', models.CharField(max_length=20)),
                ('numer_umowy', models.IntegerField()),
                ('data_zatrudnienia', models.DateField()),
                ('data_zwolnienia', models.DateField(null=True)),
                ('koniec_umowy', models.DateField()),
                ('dostepnosc_dostawcy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zarobki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okres_od', models.DateField()),
                ('okres_do', models.DateField()),
                ('przepracowane_godziny', models.IntegerField()),
                ('stawka_godzinowa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_zamowienia', models.BooleanField()),
                ('dane_platnosci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.daneplatnosci')),
                ('dostawcy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.dostawcy')),
            ],
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_produktu', models.CharField(max_length=15)),
                ('cena', models.IntegerField()),
                ('nazwa_produktu', models.CharField(max_length=300)),
                ('restouracja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.restouracje')),
            ],
        ),
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.IntegerField()),
                ('nazwisko', models.IntegerField()),
                ('adres_dostawy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.adresdostawy')),
                ('dane_kontaktowe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.danekontaktowe')),
            ],
        ),
        migrations.AddField(
            model_name='dostawcy',
            name='status_dostawcy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.statusdostawcy'),
        ),
        migrations.AddField(
            model_name='dostawcy',
            name='zarobk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.zarobki'),
        ),
        migrations.AddField(
            model_name='daneplatnosci',
            name='id_klienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.klienci'),
        ),
        migrations.CreateModel(
            name='AdresyRestouracji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField()),
                ('restouracja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.restouracje')),
            ],
        ),
    ]
