# Generated by Django 3.2a1 on 2021-01-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdresDostawy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=45)),
                ('ulica', models.CharField(max_length=45, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdresyZamieszkania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=10)),
                ('ulica', models.CharField(max_length=45, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaneKontaktowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_telefonu', models.CharField(max_length=9)),
                ('adres_mailowy', models.EmailField(max_length=45)),
                ('fax', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanePlatnosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_platnosci', models.DateField()),
                ('metoda_platnosci', models.CharField(choices=[('BLIK', 'Blik'), ('GOTÓWKA', 'Przy odbiorze'), ('PRZELEW', 'Przelew')], default='GOTÓWKA', max_length=15)),
                ('status_platnosci', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dostawcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
                ('pesel', models.CharField(max_length=11)),
                ('adresy_zamieszkania_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.adresyzamieszkania')),
                ('dane_kontaktowe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.danekontaktowe')),
            ],
            options={
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('adres_dostawy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to='jedzenieonline.adresdostawy')),
                ('dane_kontaktowe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to='jedzenieonline.danekontaktowe')),
            ],
            options={
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='Restauracje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_restauracji', models.CharField(max_length=45)),
                ('numer_telefonu', models.CharField(max_length=9)),
                ('nip', models.CharField(max_length=12)),
            ],
            options={
                'ordering': ('nazwa_restauracji',),
            },
        ),
        migrations.CreateModel(
            name='StatusDostawcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_umowy', models.CharField(max_length=20)),
                ('numer_umowy', models.IntegerField()),
                ('data_zatrudnienia', models.DateField()),
                ('data_zwolnienia', models.DateField(null=True)),
                ('koniec_umowy', models.DateField()),
                ('dostepnosc_dostawcy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zarobki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okres_od', models.DateField()),
                ('okres_do', models.DateField()),
                ('przepracowane_godziny', models.IntegerField()),
                ('stawka_godzinowa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_zamowienia', models.BooleanField()),
                ('dane_platnosci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='jedzenieonline.daneplatnosci')),
                ('dostawcy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='jedzenieonline.dostawcy')),
                ('klient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='jedzenieonline.klienci')),
            ],
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_produktu', models.CharField(choices=[('PIZZA', 'pizza'), ('BURGER', 'burger'), ('KEBAB', 'kebab'), ('SUSHI', 'sushi')], max_length=10)),
                ('nazwa_produktu', models.CharField(max_length=45)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=14)),
                ('restauracja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='jedzenieonline.restauracje')),
            ],
        ),
        migrations.AddField(
            model_name='dostawcy',
            name='status_dostawcy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.statusdostawcy'),
        ),
        migrations.AddField(
            model_name='dostawcy',
            name='zarobki_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.zarobki'),
        ),
        migrations.AddField(
            model_name='daneplatnosci',
            name='id_klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dane_platnosci', to='jedzenieonline.klienci'),
        ),
        migrations.CreateModel(
            name='AdresyRestauracji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=45, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField(null=True)),
                ('restauracja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresy_restauracji', to='jedzenieonline.restauracje')),
            ],
        ),
    ]
