# Generated by Django 3.1.3 on 2020-12-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danekontaktowe',
            name='adres_mailowy',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='klienci',
            name='imie',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='klienci',
            name='nazwisko',
            field=models.CharField(max_length=45),
        ),
    ]
