# Generated by Django 3.1.3 on 2020-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0002_auto_20201207_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='typ_produktu',
            field=models.CharField(choices=[('pizza', 'pizza'), ('hamburger', 'hamburger'), ('kebab', 'kebab')], max_length=10),
        ),
    ]
