# Generated by Django 3.1.3 on 2020-12-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0003_auto_20201222_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
