# Generated by Django 3.1.3 on 2020-12-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0005_auto_20201231_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='klient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jedzenieonline.klienci'),
            preserve_default=False,
        ),
    ]
