# Generated by Django 3.1.3 on 2021-01-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0006_zamowienia_klient_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dostawcy',
            options={'ordering': ('nazwisko',)},
        ),
        migrations.AlterModelOptions(
            name='klienci',
            options={'ordering': ('nazwisko',)},
        ),
        migrations.AlterModelOptions(
            name='restouracje',
            options={'ordering': ('nazwa_restouracji',)},
        ),
        migrations.AlterField(
            model_name='adresdostawy',
            name='numer_lokalu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adresyrestouracji',
            name='kod_pocztowy',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='adresyrestouracji',
            name='numer_lokalu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adresyrestouracji',
            name='restouracja_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresy_restouracji', to='jedzenieonline.restouracje'),
        ),
        migrations.AlterField(
            model_name='adresyzamieszkania',
            name='kod_pocztowy',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='adresyzamieszkania',
            name='numer_lokalu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='daneplatnosci',
            name='id_klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dane_platnosci', to='jedzenieonline.klienci'),
        ),
        migrations.AlterField(
            model_name='daneplatnosci',
            name='metoda_platnosci',
            field=models.CharField(choices=[('BLIK', 'Blik'), ('GOTÓWKA', 'Przy odbiorze'), ('PRZELEW', 'Przelew')], default='GOTÓWKA', max_length=15),
        ),
        migrations.AlterField(
            model_name='daneplatnosci',
            name='status_platnosci',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dostawcy',
            name='adresy_zamieszkania_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.adresyzamieszkania'),
        ),
        migrations.AlterField(
            model_name='dostawcy',
            name='dane_kontaktowe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.danekontaktowe'),
        ),
        migrations.AlterField(
            model_name='dostawcy',
            name='status_dostawcy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.statusdostawcy'),
        ),
        migrations.AlterField(
            model_name='dostawcy',
            name='zarobk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawcy', to='jedzenieonline.zarobki'),
        ),
        migrations.AlterField(
            model_name='klienci',
            name='adres_dostawy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to='jedzenieonline.adresdostawy'),
        ),
        migrations.AlterField(
            model_name='klienci',
            name='dane_kontaktowe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to='jedzenieonline.danekontaktowe'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='nazwa_produktu',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='restouracja_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='jedzenieonline.restouracje'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='typ_produktu',
            field=models.CharField(choices=[('PIZ', 'pizza'), ('BUR', 'burger'), ('KEB', 'kebab'), ('SUS', 'sushi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='restouracje',
            name='nip',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='restouracje',
            name='numer_telefonu',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='zamowienia',
            name='dane_platnosci_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='jedzenieonline.daneplatnosci'),
        ),
        migrations.AlterField(
            model_name='zamowienia',
            name='dostawcy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='jedzenieonline.dostawcy'),
        ),
        migrations.AlterField(
            model_name='zamowienia',
            name='klient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='jedzenieonline.klienci'),
        ),
    ]
