# Generated by Django 3.1.3 on 2021-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0007_auto_20210123_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostawcy',
            name='imie',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dostawcy',
            name='nazwisko',
            field=models.CharField(max_length=20),
        ),
    ]
