# Generated by Django 3.1.3 on 2021-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0008_auto_20210123_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostawcy',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
    ]
