# Generated by Django 3.1.3 on 2021-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0009_auto_20210123_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klienci',
            options={},
        ),
        migrations.AlterField(
            model_name='produkty',
            name='typ_produktu',
            field=models.CharField(choices=[('PIZZA', 'pizza'), ('BURGER', 'burger'), ('KEBAB', 'kebab'), ('SUSHI', 'sushi')], max_length=10),
        ),
    ]
