# Generated by Django 3.1.3 on 2021-01-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0010_auto_20210123_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klienci',
            options={'ordering': ('nazwisko',)},
        ),
    ]
