# Generated by Django 3.1.5 on 2021-01-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0011_auto_20210123_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dostawcy',
            old_name='zarobk_id',
            new_name='zarobki_id',
        ),
    ]
