# Generated by Django 3.1.5 on 2021-01-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenieonline', '0012_auto_20210123_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresyRestauracji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=45, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='restauracje',
            options={'ordering': ('nazwa_restauracji',)},
        ),
        migrations.RenameField(
            model_name='produkty',
            old_name='restouracja_id',
            new_name='restauracja_id',
        ),
        migrations.RenameField(
            model_name='restauracje',
            old_name='nazwa_restouracji',
            new_name='nazwa_restauracji',
        ),
        migrations.RenameModel(
            old_name='Restouracje',
            new_name='Restauracje',
        ),
        migrations.DeleteModel(
            name='AdresyRestouracji',
        ),
        migrations.AddField(
            model_name='adresyrestauracji',
            name='restauracja_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresy_restauracji', to='jedzenieonline.restauracje'),
        ),
    ]
